[package]
edition = "2021"
name = "dgg"
version = "0.1.0"

[dependencies]
serde = {version = "1.0", default-features = false, features = ["derive", "alloc"], optional = true}

[features]
serde = ["dep:serde"]

# default = ["serde"]
